### ISSUE TITLE
Pakkende subtitel

### ISSUE THREAD

**Issue by joostf** [Remy2072/user-needs#25]
https://github.com/Remy2072/user-needs/blob/c8d1489a87250b030d805a19006a12d64b999562/src/lib/Heading.svelte#L3

_Georganiseerde gastcolleges_ klinkt wat saai.

Zoiets?
_Talks door experts uit het vakgebied_

**Comment by Remy2072** [comment]
Kort maar krachtig :)
<img width="330" alt="Scherm­afbeelding 2024-12-11 om 17 25 08" src="https://github.com/user-attachments/assets/4c3b5912-8ba7-4cfc-83f0-575cc10d25a6" />
